### ISSUE TITLE
EU_433 OTAA JOIN Fail - patch

### ISSUE THREAD

**Issue by OndrejKnebl** [xoseperez/basicstation#11]
Hello,
I own a RAK5146L concentrator, which I want to operate in the EU_433 frequency plan. I ran into a problem while testing this concentrator with the LoRa Basics™ Station for Docker. With OTAA, the JOIN procedure does not work and there is a message in the log statements on LBS:
`basicstation  | 2023-08-24 04:59:32.001 [S2E:WARN] Received 'dnmsg' before 'router_config' - dropped`

So I started searching and found a hotfix for this issue:
[https://github.com/lorabasics/basicstation/issues/162](https://github.com/lorabasics/basicstation/issues/162)

I tried applying this patch. The JOIN procedure now works and so does the LoRaWAN node.

Thank you for your time and best regards,
Andy Knebl

**Comment by xoseperez** [comment]
Thank you!
Fixed in v2.6.2
