### ISSUE TITLE
OpenWRT compilation

### ISSUE THREAD

**Issue by techatreyo** [xoseperez/basicstation#15]
**Can I compile this repo?

or let me explain in deep , can I configure basicstation in openwrt based chirpstack gateway OS ?**

**Comment by xoseperez** [comment]
Hello @techatreyo 
This repo builds a docker image for the BasicStation packet forwarder by Semtech. You should go to the source (https://github.com/lorabasics/basicstation/) to compile the binaries for OpenWRT.

On the other hand ChirpStackOS already provides UDP Forwarder and MQTT Forwarder to connect to external LNS. If you really need BasicStation you should probably ask in the ChirpStack forums.

**Comment by techatreyo** [comment]
Thanks for the response.
