### ISSUE TITLE
Random reboots

### ISSUE THREAD

**Issue by rjwelling2** [xoseperez/basicstation#3]
To capture the issue I put in the forum,

My Balena Basicstation, deploy with this code is suffering from random reboots restoring the service afterwards. 

//

The time drift is a known issue but I don’t think it’s the cause of the reboot. In the last log it looks like it a network issue:

<basicstation> 2022-06-16 12:02:11.820 [AIO:ERRO] Recv failed: NET - Connection was reset by peer

Then it tries to connect again but the concentrator does not reset and if fails to start it over again. This is a bug in my code. It then reboots the service and works OK. The whole process takes almost 2 minutes. Not good.

**Comment by xoseperez** [comment]
Since v2.3.4 the basicstation process should be able to reset the concentrator after a misbehaviour like that (that is, without the need to reboot the container). The connection error is harder to tackle, mind it could very well be something outside the scope of the container...
