### ISSUE TITLE
Send failed: X509 - Certificate verification failed

### ISSUE THREAD

**Issue by chaudhariatul** [xoseperez/basicstation#4]
While connecting RAK7371 to Things Stack running on a localhost in docker container these are the errors I get on the basicstation container.

The root certificate created while creating self-signed certificates is added to /usr/local/share/ca-certificates/ and  `sudo update-ca-certificates`

I'm running this on a 64 bit raspibian on Raspberry Pi 4B with 8GB ram.

```
basicstation    | key usage  2022-08-12 05:32:20.606 [CUP:VERB] Retrieving update-info from CUPS https://192.168.0.247:443...
basicstation    | 2022-08-12 05:32:20.607 [CUP:DEBU] CUPS Request: {"router":"dca6:32ff:fec5:abba","cupsUri":"https://192.168.0.247:443","tcUri":null,"cupsCredCrc":3844209922,"tcCredCrc":2077607535,"station":"2.0.6(corecell/stdn) 2022-08-02 06:48:52","model":"corecell","package":null,"keys":[]}
basicstation    | 2022-08-12 05:32:20.619 [AIO:ERRO] [4] Send failed: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
basicstation    | 2022-08-12 05:32:20.619 [AIO:DEBU] [4] HTTP connection shutdown...
basicstation    | 2022-08-12 05:32:20.619 [CUP:INFO] Interaction with CUPS failed - retrying in 1m
basicstation    | 2022-08-12 05:32:20.619 [TCE:INFO] Starting TC engine
basicstation    | 2022-08-12 05:32:20.619 [TCE:ERRO] No TC URI configured
basicstation    | 2022-08-12 05:32:20.619 [TCE:INFO] Router rejected or retry limit reached. Invoking CUPS.
basicstation    | 2022-08-12 05:32:20.619 [TCE:INFO] Terminating TC engine
basicstation    | 2022-08-12 05:32:20.619 [CUP:INFO] Starting a CUPS session in 60 seconds.
```

**Comment by xoseperez** [comment]
Hi @chaudhariatul !

Not sure if you are already doing it like this but: since you are using CUPS you should define the CUPS_TRUST variable when creating your basicstation container (in the `docker-compose.yml` file, for instance). The content of the variable should be a one-liner of the root certificate, someting you can get by:

```
cat <path_to_ca.pem_file> | tr -d '\n'
```

**Comment by chaudhariatul** [comment]
Hi @xoseperez , yes I have tried as your document suggests to use the certificate in one line.
I have also added the root certificate created from this step to the linux host where I'm running the basicstation.

https://www.thethingsindustries.com/docs/getting-started/installation/certificates/

**Comment by xoseperez** [comment]
Hi @chaudhariatul. The BasicStation container does not have access to its root certificates folder, s that step is unneeded. The error suggests the certificate is wrong. If you can login into the stack webUI without problem (after accepting the self-signed certificate) then they have been created right.Double check that you are correctly generating the one-line cert from the ca.pem file used in your The Things Stack instance. 
Also, check that you are accessing the The Things Stack instance using the hostname you used for the certificate, it should be the same hostname/IP you are using to access the UI.

**Comment by chaudhariatul** [comment]
Hi @xoseperez ,

Is there a way to skip verification?

`basicstation    | 2022-08-22 01:37:48.015 [AIO:INFO] TLS server certificate verification failed: The certificate Common Name (CN) does not match with the expected CN`

**Comment by xoseperez** [comment]
No, there is no way and I guess that's the point. 
It certainly looks like the IP you are using to access the TTS (192.168.0.47) is not the one the certificate was generated against. How are you accessing the TTS web UI? You could try using the same IP or domain name.

**Comment by chaudhariatul** [comment]
Hi @xoseperez ,

I created the certificates using cfssl and this as the cert.json. In the web ui in the browser I'm accessing using the same IP.

```
{
  "hosts": ["192.168.0.47"],
  "names": [
    {"C": "US", "ST": "CA", "L": "SJ", "O": "Tech"}
  ]
}
```

This maybe an issue with Thingstack open source: https://www.thethingsnetwork.org/forum/t/rak2287-with-open-source-stack-on-localhost/58561

**Comment by xoseperez** [comment]
Hi @chaudhariatul, sorry it took me some time to debug the issue. I found using an IP is somewhat limited on the options it offers. I had to tweak the way the certificate is being created. You can check how I am doing it here: 

https://github.com/xoseperez/the-things-stack-docker/blob/b650dbf2673318c5e78d71b17a2a07ab50736e91/runner/entrypoint.sh#L115-L119

But, even this way not all combinations are working. This tables tries to summarize my tests, hope it can help you find a working approach:

|BasicStation<br />configuration|If Common Name is<br />an IP|If Common Name is<br />a domain name|
|---|:-:|:-:|
|Using localhost: LNS<sup>1</sup>|OK|OK|
|Using localhost: CUPS<sup>1</sup>|ERROR (Common Name mismatch)|OK<sup>2</sup>|
|Using localhost: Web UI|OK|OK|
|Using IP: LNS|ERROR (Common Name mismatch)|ERROR (Common Name mismatch)|
|Using IP: CUPS|ERROR (CA check fail)|ERROR (CA check fail)|
|Using IP: Web UI|OK|OK<sup>3</sup>|
|Using domain name: LNS|ERROR (Common Name mismatch)|OK|
|Using domain name: CUPS|ERROR (CA check fail)|OK|
|Using domain name: Web UI|OK<sup>4</sup>|OK|

1. Basicstation in the same machine as TTS and using network_mode host.
2. Works only if the domain name resolves OK from the basicstation container (CUPS response redirects to `wss://<domain_name>:8887`)
3. User gets redirected to `https://<domain_name>` after login, hence domain name must resolve to the IP.
4. User gets redirected to `https://<ip>` after login, hence domain name must resolve to the same IP.

So:

1. **Using a domain name for your machine is the best option. Set certificate common name to that name. The name should resolve from the same machine and from the network that will be accessing the server. Use the same domain name everywhere.**
2. If you cannot have a domain name, you can use the IP of the machine as certificate common name. If your BasicStation container is in the same machine set it to network_mode host and use LNS pointing to `wss://localhost:8887`. CUPS does not work. This is OK for isolated standalone gateways (packet forwarder and network server).

**Comment by chaudhariatul** [comment]
@xoseperez I sincerely appreciate your efforts here! 

I will definitely try this today and update you!

**Comment by chaudhariatul** [comment]
Hi @xoseperez I'm still getting the same error 

```
basicstation    | 2022-08-28 02:42:55.314 [AIO:INFO] TLS server certificate verification failed: The certificate Common Name (CN) does not match with the expected CN
```

kindly share your ca.json and cert.json example and the cfssl commands used to create the certs.

**Comment by xoseperez** [comment]
I have a pi-hole running on the same network. Used that to assign a name to the raspberry under a domain of mine. It should resolve from your BasicStation container and from the PC you us to access the TTS. 

lns.example.com A 192.168.0.247

And then use that same domain name in your ttn-lw-stack.yml file. If your basicstation container is in the same machine as the TTS, just use wss://localhost:8887 as your LNS server (set the container to network_mode host so localhost resolves to the host).

**Comment by chaudhariatul** [comment]
@xoseperez Perfect! 
That worked!

**Comment by xoseperez** [comment]
Great!!
So good you finally made it work!

**Comment by beitler** [comment]
Just for future reference, there could be another approach to address the issue. LoRa Basics Station allows to disable the server name indication (SNI) check by setting the environment variable `TLS_SNI=false`. The SNI check is mostly needed when public CAs are used in your security architecture (as it is the case on the public TTN network, where the certificates are signed by Let's Encrypt). When you operate your own CA, then just checking the validity of the server certificate is enough in most scenarios. Hence, it is safe to set `TLS_SNI=false` whenever private CAs are used. Maybe you can give that a try?

**Comment by xoseperez** [comment]
Sure @beitler, will test it and update the docs.
Thanks for sharing!

**Comment by xoseperez** [comment]
Tested all the scenarios where it was not working before and they all work with "TLS_SNI: false" in the environment section.
Thanks again @beitler !
Will update the documentation now.
